version: '3'
volumes:
  mongo-db:
services:
  node-server:
    build:
      context:
        .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: ./src
        target: /home/node/app/src
    command: npm run start:dev
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file:
      - .env
    volumes:
      - type: volume
        source: mongo-db
        target: /data/db