version: '3'
# volumes:
#   db:

services:
  node-server:
    build:
      context:
        .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src
        target: /home/node/app/src
    command: npm run start:dev

  db:
    image: postgres:17-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    env_file:
      - .env
    # environment:
    #   PGDATA: /data/postgres
    # volumes:
    #   - db:/data/postgres
    ports:
      - 5332:5432
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
